=== Davide-Marchese/MarcheseDavideSistemiBibliotecari/SistemaBibliotecario2/utenti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="utenti">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="utente" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nome" type="xs:string"></xs:element>
                            <xs:element name="cognome" type="xs:string"></xs:element>
                            <xs:element name="dataNascita" type="xs:date"></xs:element>
                            <xs:element name="luogoNascita" type="xs:string"></xs:element>
                            <xs:choice>
                                <xs:element name="codiceFiscale">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:length value="16"></xs:length>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:element>
                                <xs:element name="partitaIva">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:length value="11"></xs:length>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:element>
                            </xs:choice>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Davide-Marchese/MarcheseDavideSistemiBibliotecari/SistemaBibliotecario2/utenti.xml
<?xml version="1.0" encoding="UTF-8"?>
<utenti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="utenti.xsd">
    <utente>
        <nome>Mario</nome>
        <cognome>Rossi</cognome>
        <dataNascita>1978-11-08</dataNascita>
        <luogoNascita>Roma</luogoNascita>
        <codiceFiscale>RSSMRA78S08H501E</codiceFiscale>
    </utente>
    <utente>
        <nome>Alberto</nome>
        <cognome>Verdi</cognome>
        <dataNascita>1987-03-14</dataNascita>
        <luogoNascita>Genova</luogoNascita>
        <partitaIva>86334519757</partitaIva>
    </utente>
    <utente>
        <nome>Paolo</nome>
        <cognome>Conti</cognome>
        <dataNascita>1994-12-30</dataNascita>
        <luogoNascita>Rovigo</luogoNascita>
        <codiceFiscale>CNTPLA94T30H620P</codiceFiscale>
    </utente>
</utenti>
